### PR TITLE
Various improvements and fixes

### PR DESCRIPTION
**Pull request by Daniel-KM**
With the modules Search, it allows to manage indexes by site and in the admin board too.

### CODE REVIEW

**Comment by jajm** [comment]
Hi Daniel,
Do you think you can split this into smaller independent pull requests ? That would make testing easier and increase the chances of the whole thing being merged.
Thanks

**Comment by Daniel-KM** [comment]
I'm a little busy, so I'll try to divide the push during the week. The other way is having somebody testing it manually. The travis error is related to a config error for php 5.6, but it works for php 7.0.

**Comment by Daniel-KM** [comment]
The conflict is related to the fact that the font-awesome fix was done here and in another pull request, that was merged.

The upgrades of this module and Search are used in many installs now, without issue.

**Comment by pols12** [comment]
Hi @Daniel-KM 
Can you try to remove a mapping element in your install? With cascaded deletion (probably commit 377aa67), I get this error:
```SQL
Doctrine\ORM\Query\QueryException: SELECT Search\Entity\SearchPage FROM Search\Entity\SearchPage Search\Entity\SearchPage INNER JOIN Search\Entity\SearchPage.job omeka_0 WHERE omeka_0.index = :omeka_1 GROUP BY Search\Entity\SearchPage.id ORDER BY Search\Entity\SearchPage.id ASC in /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41
Stack trace:
#0 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(483): Doctrine\ORM\Query\QueryException::dqlError(&#039;SELECT Search\\E...&#039;)
#1 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1042): Doctrine\ORM\Query\Parser-&gt;semanticalError(&#039;line 0, col 127...&#039;)
#2 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1734): Doctrine\ORM\Query\Parser-&gt;JoinAssociationPathExpression()
#3 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1674): Doctrine\ORM\Query\Parser-&gt;JoinAssociationDeclaration()
#4 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1569): Doctrine\ORM\Query\Parser-&gt;Join()
#5 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(1292): Doctrine\ORM\Query\Parser-&gt;IdentificationVariableDeclaration()
#6 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(874): Doctrine\ORM\Query\Parser-&gt;FromClause()
#7 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(843): Doctrine\ORM\Query\Parser-&gt;SelectStatement()
#8 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(268): Doctrine\ORM\Query\Parser-&gt;QueryLanguage()
#9 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(351): Doctrine\ORM\Query\Parser-&gt;getAST()
#10 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(281): Doctrine\ORM\Query\Parser-&gt;parse()
#11 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(293): Doctrine\ORM\Query-&gt;_parse()
#12 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(962): Doctrine\ORM\Query-&gt;_doExecute()
#13 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(917): Doctrine\ORM\AbstractQuery-&gt;executeIgnoreQueryCache(NULL, 1)
#14 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(720): Doctrine\ORM\AbstractQuery-&gt;execute(NULL, 1)
#15 /var/www/html/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Tools/Pagination/Paginator.php(171): Doctrine\ORM\AbstractQuery-&gt;getResult(1)
#16 /var/www/html/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(245): Doctrine\ORM\Tools\Pagination\Paginator-&gt;getIterator()
#17 /var/www/html/omeka-s/application/src/Api/Manager.php(221): Omeka\Api\Adapter\AbstractEntityAdapter-&gt;search(Object(Omeka\Api\Request))
#18 /var/www/html/omeka-s/application/src/Api/Manager.php(59): Omeka\Api\Manager-&gt;execute(Object(Omeka\Api\Request))
#19 /var/www/html/omeka-s/application/src/Mvc/Controller/Plugin/Api.php(63): Omeka\Api\Manager-&gt;search(&#039;search_pages&#039;, Array, Array)
#20 /var/www/html/omeka-s/modules/Solr/src/Controller/Admin/MappingController.php(256): Omeka\Mvc\Controller\Plugin\Api-&gt;search(&#039;search_pages&#039;, Array)
#21 /var/www/html/omeka-s/modules/Solr/src/Controller/Admin/MappingController.php(172): Solr\Controller\Admin\MappingController-&gt;searchSearchPages(Object(Solr\Api\Representation\SolrNodeRepresentation))
#22 /var/www/html/omeka-s/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Solr\Controller\Admin\MappingController-&gt;deleteConfirmAction()
…
```

**Comment by Daniel-KM** [comment]
@pols12 The issue was in https://github.com/Daniel-KM/Omeka-S-module-Search/commit/9fd224d5bb4e6c6927f4e410b10c5d92297ee560 and was fixed in https://github.com/Daniel-KM/Omeka-S-module-Search/commit/0072bc703b7efded4c7967609c555d2c14bde8dd. It was visible only in some cases. 
I merged all pr and fixed various issues, and added a button to map all properties. It's a lot more simple now to create a node with all indexes.

**Comment by Daniel-KM** [comment]
@pols12 I updated your pr for cascaded linked values for the item sets, but not yet fully tested.

**Comment by pols12** [comment]
Thank you for your work @Daniel-KM.
My edits contained several issues, but I’ve forgotten what they are. Indeed, I’ve made all my fixes in [a separate module](/pols12/omeka-s-module-SolrImprovements) that extends this Solr version.

I’ve no time to update my PR (probably not before several months), but you can of course pick in that module all that you need.

**Comment by Daniel-KM** [comment]
@pols12 I merged your module and added some new features too (to reindex and to map). [Search](https://github.com/Daniel-KM/Omeka-S-module-Search), [PslSearchForm](https://github.com/Daniel-KM/Omeka-S-module-PslSearchForm) and the theme [Psl](https://github.com/Daniel-KM/Omeka-S-theme-Psl) are updated too. There is some work to do, but it works for now.

**Comment by Daniel-KM** [comment]
The travis tests are fine, the issue is related to the compilation of php-solr with php 7.2 on the virtual test machine. The packaged version of php-solr works.

**Comment by pols12** [comment]
I’ve not tested this specific branch, but at home, I’ve no issue with Solr 7.2.

I just needed to manually configure `__text__` field to make plain text search working.

**Comment by Daniel-KM** [comment]
Where do you configure __text__ ?

**Comment by pols12** [comment]
Default search field is defined in solrconfig.xml:
```xml
  <initParams path="/update/**,/query,/select,/tvrh,/elevate,/spell,/browse">
    <lst name="defaults">
      <str name="df">_text_</str>
    </lst>
  </initParams>
```
Default is `_text_` (only one underscore, sorry for previous information).

It is defined like this by default in node config:
```xml
  <field name="_text_" type="text_general" multiValued="true" indexed="true" stored="false"/>
```

You just have to set copy fields:
```xml
  <copyField source="dcterms_title_txt_fr" dest="_text_"/>
  <copyField source="dcterms_description_txt_fr" dest="_text_"/>
  …

<!-- May be defined for all fields: -->
  <copyField source="*" dest="_text_"/>
```

**Pull request closed without merging**
